<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        
        
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="16.2.0" />
        <PackageReference Include="Dapper" Version="2.1.79" />
        <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Ee.Ebs.Data.EfCore\Ee.Ebs.Data.EfCore.csproj" />
      <ProjectReference Include="..\Ee.Ebs.Domain\Ee.Ebs.Domain.csproj" />
    </ItemGroup>

</Project>
